listen: ":53"
zones:
  - domain: "dstat.coffee"
    ip: "1.2.3.4"
    ttl: 300
    subs:
      - name: "www"
        ip: "1.2.3.4"
      - name: "mail"
        ip: "1.2.3.4"
      - name: "api"
        ip: "1.2.3.4"
