listen: ":53"
zones:
  - domain: "dstat.coffee"
    ips:
      - "172.245.14.250"
    ttl: 300
    subs:
      - name: "www"
        ips:
          - "172.245.14.250"
      - name: "mail"
        ip: "172.245.14.250"
      - name: "api"
        ip: "172.245.14.250"
